# Generated by Django 6.0.7 on 2026-07-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_revenue_cents', models.IntegerField(default=0)),
                ('total_cost_cents', models.IntegerField(default=0)),
                ('total_profit_cents', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=120)),
                ('unit_snapshot', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('selling_price_cents_snapshot', models.IntegerField()),
                ('cost_per_unit_cents_snapshot', models.IntegerField()),
                ('line_revenue_cents', models.IntegerField()),
                ('line_cost_cents', models.IntegerField()),
                ('line_profit_cents', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
