# Generated by Django 6.0.7 on 2026-07-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('opening', 'Opening'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_reversal', 'Sale reversal'), ('manual_increase', 'Manual increase'), ('manual_decrease', 'Manual decrease'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('personal_use', 'Personal use')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('resulting_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchases.purchase')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
