# Generated by Django 6.0.7 on 2026-07-11 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_purchased', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purchase_unit', models.CharField(max_length=20)),
                ('units_per_purchase_unit', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('total_cost_cents', models.IntegerField()),
                ('calculated_unit_cost_cents', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product_cost_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.product')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
